### ISSUE TITLE
Add less frequently use verbs as values e.g. abrogates, empowers, reaffirms

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/cipm-resolutions#4]
There are some less frequently used keywords which appear in these resolutions, such as abrogates, empowers, reaffirms, etc. 

We should use them as verbs in the repository.

_Originally posted by @anermina in https://github.com/metanorma/cipm-resolutions/pull/2#discussion_r501056195_

**Comment by anermina** [comment]
Besides from the above mentioned, following terms will also be used as verbs in CGPM and CIPM .yaml files:
- accepts
- elects
- authorizes
- charges
- states
- observing
- remarks
- judges
- referring
- sanctions
- acting

**Comment by anermina** [comment]
Done in https://github.com/metanorma/cipm-resolutions/pull/5 for CIPM and https://github.com/metanorma/cgpm-resolutions/pull/17 for CGPM.
